# A Github Action which uses node 12, and runs the npm run gulp command, and if we have any diff we commit with "Recompile theme" with the github user and email of autoupdater@moody.utexas.edu and same name.
name: Compile theme

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Compile theme
        run: npm run gulp
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: autoupdater
          author_email: autoupdater@moody.utexas.edu
          message: 'Recompile theme'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}